services:
  user-service:
    depends_on:
      - init-kafka
    build:
      context: .
      args:
        JAR_PATH: user-service/target
    ports:
      - "8080:8080"
  package-service:
    depends_on:
      - init-kafka
    build:
      context: .
      args:
        JAR_PATH: package-service/target
    ports:
      - "8081:8080"

  kafka:
    image: &kafka-image apache/kafka:3.8.1
    ports:
      - "9092:9092"
      - "9093:9093"
    environment:
      - KAFKA_NODE_ID=0
      - KAFKA_PROCESS_ROLES=controller,broker
      - KAFKA_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://:9092
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR=1
      - KAFKA_TRANSACTION_STATE_LOG_MIN_ISR=1
      - KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS=0
      - KAFKA_NUM_PARTITIONS=3
    healthcheck:
      test: ["CMD", "/opt/kafka/bin/kafka-topics.sh", "--bootstrap-server=localhost:9092", "--list"]
      start_period: 15s
      interval: 10s

  init-kafka:
    image: *kafka-image
    entrypoint:
      - /bin/bash
      - -c
      - "
        /opt/kafka/bin/kafka-topics.sh --create --if-not-exists --topic accepted --replication-factor=1 --partitions=1 --bootstrap-server kafka:9092
        && /opt/kafka/bin/kafka-topics.sh --create --if-not-exists --topic validated --replication-factor=1 --partitions=1 --bootstrap-server kafka:9092
        && /opt/kafka/bin/kafka-topics.sh --create --if-not-exists --topic declined --replication-factor=1 --partitions=1 --bootstrap-server kafka:9092
        && /opt/kafka/bin/kafka-topics.sh --create --if-not-exists --topic sent --replication-factor=1 --partitions=1 --bootstrap-server kafka:9092
        && /opt/kafka/bin/kafka-topics.sh --bootstrap-server kafka:9092 --list
        "
    depends_on:
      kafka:
        condition: service_healthy
